#pragma once

#define F4SEVR_DLSS_VERSION_MAJOR 1
#define F4SEVR_DLSS_VERSION_MINOR 0
#define F4SEVR_DLSS_VERSION_PATCH 0
#define F4SEVR_DLSS_VERSION_VERSTRING "1.0.0"

// For compatibility with template
#define F4SEVRTEMPLATE_VERSION_MAJOR F4SEVR_DLSS_VERSION_MAJOR
#define F4SEVRTEMPLATE_VERSION_MINOR F4SEVR_DLSS_VERSION_MINOR
#define F4SEVRTEMPLATE_VERSION_PATCH F4SEVR_DLSS_VERSION_PATCH
#define F4SEVRTEMPLATE_VERSION_VERSTRING F4SEVR_DLSS_VERSION_VERSTRING